version: "3.8"

services:

  localstack:
    build:
      context: ./docker/localstack/
    image: snoindex-localstack
    environment:
      - AWS_DEFAULT_REGION=us-west-2
      - AWS_ACCESS_KEY_ID=testing
      - AWS_SECRET_ACCESS_KEY=testing
      - SERVICES=sqs
      - LS_LOG=warn
    ports:
      - "4566:4566"
    volumes:
      - "./docker/localstack/create_localstack.sh:/docker-entrypoint-initaws.d/create_localstack.sh"

  opensearch:
    build:
      context: ./docker/opensearch/
    image: snoindex-opensearch
    environment:
      - "discovery.type=single-node"
      - "node.name=opensearch-node1"
      - "OPENSEARCH_JAVA_OPTS=-Xms256m -Xmx256m"
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
      - "DISABLE_SECURITY_PLUGIN=true"
    volumes:
      - "./config/opensearch/opensearch.yml:/usr/share/opensearch/config/opensearch.yml"
    ports:
      - "9200:9200"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536

  snoindex:
    build:
      context: .
      dockerfile: ./docker/snoindex/Dockerfile
    image: snoindex
    volumes:
      - ".:/snovault-index"
      - "/snovault-index/src/snovault_index.egg-info"
    command: pytest --cov=snoindex -s -o junit_family=legacy --junitxml=./.test-results/junit.xml --cov-append -m 'integration'
    depends_on:
      - localstack
      - opensearch
