version: 2.1

workflows:
  snoindex-tests:
    jobs:
      - lint
      - snoindex-pytest:
          requires:
            - lint

jobs:
  lint:
    docker:
      - image: cimg/python:3.9
    working_directory: ~/snovault-index
    steps:
      - checkout
      - run: pip install pre-commit==2.17.0
      - run: pre-commit run --all-files

  snoindex-pytest:
    machine:
      image: ubuntu-2004:202111-02
      docker_layer_caching: true
    resource_class: medium
    working_directory: ~/snovault-index
    steps:
      - checkout
      - run:
          name: Build Docker images
          command: docker-compose -f docker-compose.test.yml build
      - run:
          name: Set folder permissions for mounted volume
          command: |
              sudo useradd -u 1444 snoindex
              sudo usermod -a -G snoindex circleci
              sudo chown -R circleci:snoindex ./
      - run:
          name: Run tests
          command: |
              docker-compose -f docker-compose.test.yml up --exit-code-from snoindex